
language: node_js
node_js:
  - '0.11'
  - '0.10'
  - '0.8'
  - '0.6'
matrix:
  fast_finish: true
  allow_failures:
  - node_js: '0.11'
  - node_js: '0.6'
services:
  - mongodb
before_install:
  - npm conf set strict-ssl false
  - cp test/TestConfig.travis.json test/TestConfig.json
before_script:
  - npm install -g jshint
  - mysql -e 'create database travis_test;'
  - mongo currency --eval 'db.addUser("travis", "test");'
  #- psql -c 'create database travis_test;' -U postgres
script:
  - ant -f build.xml ci
notifications:
  email:
    recipients:
      - simon@simonemms.com
    on_success: change
    on_failure: always